"""
Base strategy class and interface for all trading strategies.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Dict, Optional, Tuple
import pandas as pd
import logging

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    direction: str  # 'long', 'short', or 'neutral'
    confidence: float  # 0.0 to 1.0
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    strategy_name: str = ""
    timestamp: Optional[pd.Timestamp] = None
    metadata: Dict = None
    
    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}
    
    def is_valid(self) -> bool:
        """Check if signal is valid for trading."""
        return (
            self.direction in ['long', 'short'] and
            0.0 <= self.confidence <= 1.0 and
            self.entry_price is not None and
            self.entry_price > 0
        )


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    Each strategy must implement generate_signal() method.
    """
    
    def __init__(self, name: str, config: Dict = None):
        self.name = name
        self.config = config or {}
        self.performance_stats = {
            'total_trades': 0,
            'winning_trades': 0,
            'losing_trades': 0,
            'total_pnl': 0.0,
            'win_rate': 0.0,
            'profit_factor': 0.0,
            'max_drawdown': 0.0,
            'avg_win': 0.0,
            'avg_loss': 0.0
        }
        self.trade_history = []
    
    @abstractmethod
    def generate_signal(
        self, 
        df: pd.DataFrame, 
        market_data: Dict
    ) -> Signal:
        """
        Generate trading signal based on market data.
        
        Args:
            df: OHLCV DataFrame with historical data
            market_data: Dict containing additional market data 
                        (funding_rate, open_interest, ticker, etc.)
        
        Returns:
            Signal object with trading recommendation
        """
        pass
    
    def update_performance(self, pnl: float, is_winner: bool):
        """Update strategy performance statistics after trade closes."""
        self.performance_stats['total_trades'] += 1
        
        if is_winner:
            self.performance_stats['winning_trades'] += 1
            self.performance_stats['avg_win'] = (
                (self.performance_stats['avg_win'] * (self.performance_stats['winning_trades'] - 1) + pnl) 
                / self.performance_stats['winning_trades']
            )
        else:
            self.performance_stats['losing_trades'] += 1
            self.performance_stats['avg_loss'] = (
                (self.performance_stats['avg_loss'] * (self.performance_stats['losing_trades'] - 1) + abs(pnl)) 
                / self.performance_stats['losing_trades']
            )
        
        self.performance_stats['total_pnl'] += pnl
        
        # Calculate win rate
        if self.performance_stats['total_trades'] > 0:
            self.performance_stats['win_rate'] = (
                self.performance_stats['winning_trades'] / self.performance_stats['total_trades']
            )
        
        # Calculate profit factor
        gross_profit = self.performance_stats['avg_win'] * self.performance_stats['winning_trades']
        gross_loss = self.performance_stats['avg_loss'] * self.performance_stats['losing_trades']
        
        if gross_loss > 0:
            self.performance_stats['profit_factor'] = gross_profit / gross_loss
        else:
            self.performance_stats['profit_factor'] = float('inf') if gross_profit > 0 else 0.0
        
        self.trade_history.append({
            'pnl': pnl,
            'is_winner': is_winner,
            'cumulative_pnl': self.performance_stats['total_pnl']
        })
    
    def get_effectiveness_score(self) -> float:
        """
        Calculate effectiveness score for meta-algorithm.
        Combines win rate, profit factor, and consistency.
        """
        stats = self.performance_stats
        
        if stats['total_trades'] < 3:
            return 0.5  # Not enough data, neutral score
        
        # Weighted combination of metrics
        win_rate_score = stats['win_rate'] * 0.4
        pf_score = min(stats['profit_factor'] / 2.0, 1.0) * 0.4  # Cap at 2.0 PF
        
        # Consistency score (based on recent trades)
        recent_trades = self.trade_history[-10:] if len(self.trade_history) >= 10 else self.trade_history
        if recent_trades:
            recent_wins = sum(1 for t in recent_trades if t['is_winner'])
            consistency = recent_wins / len(recent_trades)
        else:
            consistency = 0.5
        
        consistency_score = consistency * 0.2
        
        return win_rate_score + pf_score + consistency_score
    
    def __repr__(self):
        return f"{self.name}(win_rate={self.performance_stats['win_rate']:.2f}, pf={self.performance_stats['profit_factor']:.2f})"
